### ISSUE TITLE
Document how to use a self-hosted relay

### ISSUE THREAD

**Issue by gabrc52** [thatmarcel/beepserv-rewrite#2]
From reading the source code, one must put the URL of the custom relay in `/var/jb/.beepserv_wsurl`. There is no documentation of this.

Upstream issue: https://github.com/beeper/phone-registration-provider/issues/31

**Comment by thatmarcel** [comment]
Thanks for the heads-up.

Commit [876e322](https://github.com/thatmarcel/beepserv-rewrite/commit/876e322054bb087cfd0a45f36dae015d9d84c823) makes it possible to also put the URL in `/var/mobile/.beepserv_relay_url` (rootful) or `/var/jb/var/mobile/.beepserv_relay_url` (rootless).

Since [a19b252](https://github.com/thatmarcel/beepserv-rewrite/commit/a19b252cbca9a5b098f5a35839b6c0deda6586d6) there are now instructions in the readme on using a self-hosted relay.
